/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp02.FacultyProfileJPanel;
import UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp02.ManageCourseListJPanel;
import UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp02.ManageStudentProfileListJPanel;
import UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp02.PerformanceReportJPanel;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class FacultyWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public FacultyWorkAreaJPanel(Business b, JPanel csp) {
        initComponents();

        business = b;
        this.CardSequencePanel = csp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCourse = new javax.swing.JButton();
        btnManageStudentProfile = new javax.swing.JButton();
        btnfacultyProfile = new javax.swing.JButton();
        btnPerformanceReport = new javax.swing.JButton();
        lblFacultyTitle = new javax.swing.JLabel();

        setForeground(new java.awt.Color(51, 51, 51));

        btnManageCourse.setBackground(new java.awt.Color(102, 153, 255));
        btnManageCourse.setFont(getFont());
        btnManageCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCourse.setText(" Manage Courses");
        btnManageCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCourse.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageCourse.setMinimumSize(new java.awt.Dimension(20, 23));
        btnManageCourse.setPreferredSize(new java.awt.Dimension(240, 30));
        btnManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourseIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageStudentProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnManageStudentProfile.setFont(getFont());
        btnManageStudentProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStudentProfile.setText("Manage Students Profiles");
        btnManageStudentProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudentProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageStudentProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageStudentProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageStudentProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentProfileActionPerformed(evt);
            }
        });

        btnfacultyProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnfacultyProfile.setFont(getFont());
        btnfacultyProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnfacultyProfile.setText("My Profile");
        btnfacultyProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnfacultyProfile.setMaximumSize(new java.awt.Dimension(145, 40));
        btnfacultyProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnfacultyProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnfacultyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacultyProfileIdentifyEventsActionPerformed(evt);
            }
        });

        btnPerformanceReport.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformanceReport.setFont(getFont());
        btnPerformanceReport.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceReport.setText("Performance Reports");
        btnPerformanceReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformanceReport.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformanceReport.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformanceReport.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformanceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportActionPerformed(evt);
            }
        });

        lblFacultyTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFacultyTitle.setText("My Faculty Profie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(btnManageStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnfacultyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerformanceReport, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblFacultyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblFacultyTitle)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfacultyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCourseIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourseIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        
        ManageCourseListJPanel mcj = new ManageCourseListJPanel(business, CardSequencePanel);
       
        CardSequencePanel.add("ManageCourses", mcj);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "ManageCourses");

    }//GEN-LAST:event_btnManageCourseIdentifyResourceAssetsActionPerformed

    private void btnManageStudentProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentProfileActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();

        ManageStudentProfileListJPanel msp = new ManageStudentProfileListJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageStudent", msp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

  
    }//GEN-LAST:event_btnManageStudentProfileActionPerformed

    private void btnfacultyProfileIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacultyProfileIdentifyEventsActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();
      
        FacultyProfileJPanel fpj = new FacultyProfileJPanel(business, CardSequencePanel);
        
        CardSequencePanel.add("FacultyProfile", fpj);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_btnfacultyProfileIdentifyEventsActionPerformed

    private void btnPerformanceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();
        
        PerformanceReportJPanel prj = new PerformanceReportJPanel(business, CardSequencePanel);
        
        CardSequencePanel.add("Performance", prj);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

}//GEN-LAST:event_btnPerformanceReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourse;
    private javax.swing.JButton btnManageStudentProfile;
    private javax.swing.JButton btnPerformanceReport;
    private javax.swing.JButton btnfacultyProfile;
    private javax.swing.JLabel lblFacultyTitle;
    // End of variables declaration//GEN-END:variables

}
