/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VehicleService;

import Business.ServiceCatalog;
import Business.VehicleDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Service;
import model.Vehicle;


/**
 *
 * @author Hyungs
 */
public class ServicesJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    ServiceCatalog serviceCatalog;
    VehicleDirectory vehicleDirectory;
    Vehicle vehicle;
    
    /**
     * Creates new form ServicesJPanel
     */
    public ServicesJPanel(JPanel container, VehicleDirectory directory, ServiceCatalog catalog) {
        initComponents();
        
        this.userProcessContainer = container;
        this.serviceCatalog = catalog;
        this.vehicleDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServiceTitle = new javax.swing.JLabel();
        lblServiceId = new javax.swing.JLabel();
        lblServiceType = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblMechanicName = new javax.swing.JLabel();
        lblServiceDuration = new javax.swing.JLabel();
        txtServiceId = new javax.swing.JTextField();
        txtServiceType = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        txtMechanicName = new javax.swing.JTextField();
        txtServiceDuration = new javax.swing.JTextField();
        btnCreateService = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblServiceTitle.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblServiceTitle.setText("Services");

        lblServiceId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblServiceId.setText("Service ID :");

        lblServiceType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblServiceType.setText("Service Type :");

        lblCost.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCost.setText("Cost :");

        lblMechanicName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMechanicName.setText("Mechanic's Name :");

        lblServiceDuration.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblServiceDuration.setText("Service Duration : ");

        txtServiceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceIdActionPerformed(evt);
            }
        });

        btnCreateService.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnCreateService.setText("Create Service");
        btnCreateService.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateServiceActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnBack.setText("<<<  Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblServiceTitle)
                .addGap(364, 364, 364))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblServiceType)
                                    .addComponent(lblCost)
                                    .addComponent(lblMechanicName)
                                    .addComponent(lblServiceDuration))
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtServiceType, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(txtCost)
                                    .addComponent(txtMechanicName)
                                    .addComponent(txtServiceDuration)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblServiceId)
                                .addGap(165, 165, 165)
                                .addComponent(txtServiceId, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(btnCreateService, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(58, 58, 58)
                .addComponent(lblServiceTitle)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceId)
                    .addComponent(txtServiceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceType)
                    .addComponent(txtServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCost)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMechanicName)
                    .addComponent(txtMechanicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceDuration)
                    .addComponent(txtServiceDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(btnCreateService, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtServiceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceIdActionPerformed

    private void btnCreateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateServiceActionPerformed
        // TODO add your handling code here:
        double cost;
        int serviceDuration;
        
        String serviceId = txtServiceId.getText();
        String serviceType = txtServiceType.getText();
        String mechanicName = txtMechanicName.getText();
        
        if (serviceId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input Service ID.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (serviceType.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input Service Type.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (mechanicName.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please input Mechanic Name.", "Warning", JOptionPane.WARNING_MESSAGE);
             return;
        }
        
        try {
            cost = Double.parseDouble(txtCost.getText());
            serviceDuration = Integer.parseInt(txtServiceDuration.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid cost and duration.", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Service s = serviceCatalog.addService();
        s.setServiceId(serviceId);
        s.setServiceType(serviceType);
        s.setCost(cost);
        s.setMechanicName(mechanicName);
        s.setServiceDuration(serviceDuration);
        
        Vehicle v = vehicleDirectory.searchByOwnerId(serviceId);
        if (v != null) {
            v.setServiceType(serviceType);
            v.setCost(cost);
        }
        

        JOptionPane.showMessageDialog(this, "Service sucessfully created.", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        txtServiceId.setText("");
        txtServiceType.setText("");
        txtCost.setText("");
        txtMechanicName.setText("");
        txtServiceDuration.setText("");

    }//GEN-LAST:event_btnCreateServiceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateService;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblMechanicName;
    private javax.swing.JLabel lblServiceDuration;
    private javax.swing.JLabel lblServiceId;
    private javax.swing.JLabel lblServiceTitle;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtMechanicName;
    private javax.swing.JTextField txtServiceDuration;
    private javax.swing.JTextField txtServiceId;
    private javax.swing.JTextField txtServiceType;
    // End of variables declaration//GEN-END:variables
}
