/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.UserAccounts.UserAccountDirectory;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hdIV
 */
public class AdminPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminPersonJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Person person;
    private final boolean edit;
            
    public AdminPersonJPanel(Business bz, JPanel jp, Person p) {
        CardSequencePanel = jp;
        this.business = bz;
        this.person = p;
        this.edit = (p != null);
        
        initComponents();
        populateFields();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtPersonId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setText("Manage Person");

        lblID.setText("ID");

        lblName.setText("Name");

        lblEmail.setText("Email");

        lblRole.setText("Role");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(txtPersonId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID)
                    .addComponent(txtPersonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRole)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnSave)
                .addContainerGap(232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // 1. Get input
        String name = txtName.getText().trim();
        String email = txtEmail.getText().trim();
        String selectedRole = (String) cmbRole.getSelectedItem();

        // 2. Validate input
        if (name.isEmpty() || email.isEmpty() || selectedRole == null) {
            JOptionPane.showMessageDialog(this, "Name, Email, and Role cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; // Stay on page on validation error
        }
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pat = Pattern.compile(emailRegex);
        if (!pat.matcher(email).matches()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; // Stay on page
        }

        Department department = business.getDepartment();
        PersonDirectory personDirectory = department.getPersonDirectory();
        StudentDirectory studentDirectory = department.getStudentDirectory();
        FacultyDirectory facultyDirectory = department.getFacultyDirectory();
        UserAccountDirectory userAccountDirectory = business.getUserAccountDirectory();

        // 3. Check for duplicate email (excluding self in edit mode)
        Person existingPersonWithEmail = personDirectory.findPersonByEmail(email);
        if (existingPersonWithEmail != null && (!edit || !existingPersonWithEmail.getPersonId().equals(person.getPersonId()))) {
            JOptionPane.showMessageDialog(this, "This email address is already registered to another person.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return; // Stay on page
        }

        // --- Perform Add or Update ---
        boolean saveSuccessful = false; // Flag to control navigation

        if (edit) {
            // --- Update existing person --- (Role change logic is complex and needs careful implementation - see previous response)
            if (person == null) {
                JOptionPane.showMessageDialog(this, "Error: No person selected for editing.", "Internal Error", JOptionPane.ERROR_MESSAGE);
                return; // Stay on page
            }

            // --- Simplified Update - Focus on Name/Email first ---
            person.setFirstName(name);
            person.setEmail(email);

          

            JOptionPane.showMessageDialog(this, "Person information updated successfully.", "Update Success", JOptionPane.INFORMATION_MESSAGE);
            saveSuccessful = true; // Assume success for now

        } else {
            // --- Add new person ---
            // *** Use new ID generation logic ***
            String idPrefix = "";
            if ("Student".equals(selectedRole)) {
                idPrefix = "S";
            } else if ("Faculty".equals(selectedRole)) {
                idPrefix = "F";
            } // Add other prefixes if needed

            if (idPrefix.isEmpty()){
                JOptionPane.showMessageDialog(this, "Invalid role selected for ID generation.", "Creation Error", JOptionPane.ERROR_MESSAGE);
                return; // Stay on page
            }

            String uniqueID = generateNextPersonId(idPrefix, personDirectory);
            // *** End new ID generation logic ***

            Person newPerson = personDirectory.newPerson(uniqueID);
            if (newPerson == null) { // Check if ID already exists or other error
                JOptionPane.showMessageDialog(this, "Failed to create new person record (possibly duplicate ID '" + uniqueID + "').", "Creation Error", JOptionPane.ERROR_MESSAGE);
                return; // Stay on page
            }
            newPerson.setFirstName(name);
            newPerson.setEmail(email);

            // Create Profile object based on role
            boolean profileCreated = false;
            if ("Student".equals(selectedRole)) {
                StudentProfile studentProfile = studentDirectory.newStudentProfile(newPerson);
                profileCreated = (studentProfile != null);
            } else if ("Faculty".equals(selectedRole)) {
                FacultyProfile facultyProfile = facultyDirectory.newFacultyProfile(newPerson);
                profileCreated = (facultyProfile != null);
            }

            if (profileCreated) {
                JOptionPane.showMessageDialog(this, "Person registered successfully!\nID: " + uniqueID + "\nName: " + name, "Registration Success", JOptionPane.INFORMATION_MESSAGE);
                saveSuccessful = true;
                // Consider creating UserAccount here as well
            } else {
                JOptionPane.showMessageDialog(this, "Person record created, but failed to create the profile ("+ selectedRole +"). Rolling back.", "Registration Warning", JOptionPane.WARNING_MESSAGE);
                personDirectory.removePerson(newPerson); // Rollback person creation
                saveSuccessful = false; // Stay on page
            }
        }

        // --- Navigate back only if save was fully successful ---
        if (saveSuccessful) {
            CardSequencePanel.remove(this);
            ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
            refreshPreviousTable(); // Refresh the list view
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPersonId;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        cmbRole.removeAllItems(); // Clear any existing items first
        cmbRole.addItem("Student");
        cmbRole.addItem("Faculty");
        
        if (edit && person != null) {
            lblTitle.setText("Edit Person Profile");
            txtPersonId.setText(person.getPersonId());
            txtName.setText(person.getFirstName());
            txtEmail.setText(person.getEmail());
            
            Department department = business.getDepartment();
            StudentDirectory sd = department.getStudentDirectory();
            FacultyDirectory fd = department.getFacultyDirectory();
            String currentRole = null;
            if (sd.findStudent(person.getPersonId()) != null) {
                 currentRole = "Student";
            } else if (fd.findFacultyByPersonId(person.getPersonId()) != null) {
                 currentRole = "Faculty";
            }
            
            if (currentRole != null) {
                 cmbRole.setSelectedItem(currentRole);
            } else {
                cmbRole.setSelectedIndex(-1);
            }
            cmbRole.setEnabled(true);
        } else {
            lblTitle.setText("Add New Person"); // Update title
            txtPersonId.setText("(Auto-generated on save)"); // Updated placeholder text
            txtName.setText("");
            txtEmail.setText("");
            
            if (cmbRole.getItemCount() > 0) {
                 cmbRole.setSelectedIndex(0);
            }
            cmbRole.setEnabled(true);
        }
    }
    
    private String generateNextPersonId(String rolePrefix, PersonDirectory personDirectory) {
        int maxNumber = 0;
        ArrayList<Person> persons = personDirectory.getPersonList(); // Assuming getPersonList() exists

        for (Person p : persons) {
            String id = p.getPersonId();
            if (id != null && id.startsWith(rolePrefix)) {
                try {
                    // Extract the numeric part after the prefix
                    String numPart = id.substring(rolePrefix.length());
                    int currentNum = Integer.parseInt(numPart);
                    if (currentNum > maxNumber) {
                        maxNumber = currentNum;
                    }
                } catch (NumberFormatException | IndexOutOfBoundsException e) {
                    // Handle IDs that don't match the expected format (e.g., old UUIDs)
                    System.err.println("Skipping improperly formatted ID during generation: " + id);
                }
            }
        }
        // Format the next number with leading zeros (e.g., 001, 010, 100)
        return rolePrefix + String.format("%03d", maxNumber + 1);
    }

    private void refreshPreviousTable() {
        Component[] components = CardSequencePanel.getComponents();
        // Iterate backwards to find the most recent ManagePersonsJPanel instance
        for (int i = components.length - 1; i >= 0; i--) {
            if (components[i] instanceof ManagePersonsJPanel) {
                ((ManagePersonsJPanel) components[i]).populateTable(); // Call the populateTable method
                return; // Found and refreshed, exit loop
            }
        }
        System.err.println("Warning: Could not find ManagePersonsJPanel in CardSequencePanel to refresh.");
    }
    }

