/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.WorkArea.StudentRole.StudentRoleWorkResp;

import Business.Business;
import Business.Profile.StudentProfile;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Hyungs
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {
    
    Business business;
    JPanel workAreaJPanel;
    UserAccount userAccount;
    

    /**
     * Creates new form StudentWorkAreaJPanel
     * 
     */
    public StudentWorkAreaJPanel(Business business, JPanel workArea, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.workAreaJPanel = workArea;
        this.userAccount = userAccount;
        
        populateFields();
        setViewMode();
   
    }
    
    private void populateFields() {
        StudentProfile sp = (StudentProfile) userAccount.getAssociatedPersonProfile();
        
        txtStudentNUID.setText(sp.getNuId());
        txtStudentName.setText(sp.getName());
        txtStudentYear.setText(sp.getYear());
        txtStudentMajor.setText(sp.getMajor());
        
        txtStudentNUID.setEnabled(false);
        txtStudentName.setEnabled(false);
        txtStudentYear.setEnabled(false);
        txtStudentMajor.setEnabled(false);
        
        lblStudentWelcome.setText("Welcome," + sp.getName() + "!");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblStudentNUID = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        txtStudentNUID = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        btnStudentBack = new javax.swing.JButton();
        lblStudentWelcome = new javax.swing.JLabel();
        lblStudentYear = new javax.swing.JLabel();
        lblStudentMajor = new javax.swing.JLabel();
        txtStudentYear = new javax.swing.JTextField();
        txtStudentMajor = new javax.swing.JTextField();
        btnStudentSave = new javax.swing.JButton();
        btnStudentUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setText("Student Profile");

        lblStudentNUID.setText("NUID : ");

        lblStudentName.setText("Name :");

        txtStudentNUID.setEditable(false);

        txtStudentName.setEditable(false);

        btnStudentBack.setText("<<< Back");
        btnStudentBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentBackActionPerformed(evt);
            }
        });

        lblStudentWelcome.setText("<Welcome Message>");

        lblStudentYear.setText("Year :");

        lblStudentMajor.setText("Major :");

        txtStudentYear.setEditable(false);

        txtStudentMajor.setEditable(false);

        btnStudentSave.setText("Save");
        btnStudentSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentSaveActionPerformed(evt);
            }
        });

        btnStudentUpdate.setText("Update");
        btnStudentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStudentBack)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStudentNUID)
                                .addGap(97, 97, 97)
                                .addComponent(txtStudentNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnStudentSave)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnStudentUpdate))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblStudentName)
                                        .addComponent(lblStudentYear)
                                        .addComponent(lblStudentMajor))
                                    .addGap(97, 97, 97)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtStudentName)
                                        .addComponent(txtStudentYear)
                                        .addComponent(txtStudentMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(174, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(lblStudentWelcome)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnStudentBack))
                .addGap(18, 18, 18)
                .addComponent(lblStudentWelcome)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentNUID)
                    .addComponent(txtStudentNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStudentName)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentYear)
                    .addComponent(txtStudentYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentMajor)
                    .addComponent(txtStudentMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentSave)
                    .addComponent(btnStudentUpdate))
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentSaveActionPerformed
        // TODO add your handling code here:
        setViewMode();
    }//GEN-LAST:event_btnStudentSaveActionPerformed

    private void btnStudentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnStudentUpdateActionPerformed

    private void btnStudentBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentBackActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout)workAreaJPanel.getLayout();
        layout.show(workAreaJPanel, "Student");

        
    }//GEN-LAST:event_btnStudentBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentBack;
    private javax.swing.JButton btnStudentSave;
    private javax.swing.JButton btnStudentUpdate;
    private javax.swing.JLabel lblStudentMajor;
    private javax.swing.JLabel lblStudentNUID;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentWelcome;
    private javax.swing.JLabel lblStudentYear;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtStudentMajor;
    private javax.swing.JTextField txtStudentNUID;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentYear;
    // End of variables declaration//GEN-END:variables

    private void setViewMode() {
        txtStudentName.setEnabled(false);
        txtStudentNUID.setEnabled(false);
        txtStudentYear.setEnabled(false);
        txtStudentMajor.setEnabled(false);
        
        btnStudentSave.setEnabled(false);
        btnStudentUpdate.setEnabled(true);
    }
    
    private void setEditMode() {
        txtStudentName.setEnabled(true);
        txtStudentYear.setEnabled(true);
        txtStudentMajor.setEnabled(true);
        
        btnStudentSave.setEnabled(true);
        btnStudentUpdate.setEnabled(false);
    }


}
