/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.WorkArea.AdminRole.AdminUserAccountsWorkResp;

import Business.Business;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hyungs
 */
public class AdminMyProfileJPanel extends javax.swing.JPanel {
    
    JPanel workArea;
    Business business;
    UserAccount userAccount;
    boolean editMode = false;

    /**
     * Creates new form AdminMyProfileJPanel
     */
    public AdminMyProfileJPanel(Business b, JPanel workArea, UserAccount ua) {
        initComponents();
        
        this.business = b;
        this.workArea = workArea;
        this.userAccount = ua;
        
        populateFields();
        setViewMode();
        
    }
        
    private void populateFields() {
        txtAPUserName.setText(userAccount.getUserLoginName());
        txtAPPassword.setText(userAccount.getPassword());
        txtAPStatus.setText(userAccount.getStatus());
        txtAPRole.setText(userAccount.getRole());
        txtAPLastActivity.setText(userAccount.getLastActivity());
        txtAPLastUpdated.setText(userAccount.getLastUpdated());
        
        txtAPUserName.setEnabled(false);
        txtAPRole.setEnabled(false);
        txtAPLastActivity.setEnabled(false);
        txtAPLastUpdated.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAPPassword = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtAPStatus = new javax.swing.JTextField();
        btnAPBack = new javax.swing.JButton();
        txtAPRole = new javax.swing.JTextField();
        btnAPUpdate = new javax.swing.JButton();
        txtAPLastActivity = new javax.swing.JTextField();
        lblAPUserName = new javax.swing.JLabel();
        txtAPLastUpdated = new javax.swing.JTextField();
        lblAPPassword = new javax.swing.JLabel();
        lblAPStatus = new javax.swing.JLabel();
        lblAPRole = new javax.swing.JLabel();
        lblAPLastAcitivity = new javax.swing.JLabel();
        lblAPLastUpdated = new javax.swing.JLabel();
        txtAPUserName = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("My Profile");

        btnAPBack.setText("<<< Back");
        btnAPBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAPBackActionPerformed(evt);
            }
        });

        btnAPUpdate.setText("Update >>>");
        btnAPUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAPUpdateActionPerformed(evt);
            }
        });

        txtAPLastActivity.setEditable(false);

        lblAPUserName.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblAPUserName.setText("User Name:");

        txtAPLastUpdated.setEditable(false);

        lblAPPassword.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblAPPassword.setText("Password :");

        lblAPStatus.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblAPStatus.setText("Status :");

        lblAPRole.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblAPRole.setText("Role :");

        lblAPLastAcitivity.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblAPLastAcitivity.setText("Last Activity :");

        lblAPLastUpdated.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblAPLastUpdated.setText("Last Updated :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAPUserName)
                                .addComponent(lblAPPassword)
                                .addComponent(lblAPStatus)
                                .addComponent(lblAPRole)
                                .addComponent(lblAPLastAcitivity)
                                .addComponent(lblAPLastUpdated))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAPUserName)
                                .addComponent(txtAPPassword)
                                .addComponent(txtAPStatus)
                                .addComponent(txtAPRole)
                                .addComponent(txtAPLastActivity)
                                .addComponent(txtAPLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAPBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAPUpdate))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPUserName)
                    .addComponent(txtAPUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPPassword)
                    .addComponent(txtAPPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPStatus)
                    .addComponent(txtAPStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPRole)
                    .addComponent(txtAPRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPLastAcitivity)
                    .addComponent(txtAPLastActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPLastUpdated)
                    .addComponent(txtAPLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAPBack)
                    .addComponent(btnAPUpdate))
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAPBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAPBackActionPerformed

    private void btnAPUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPUpdateActionPerformed
        // TODO add your handling code here:
        if (!editMode) {
            setEditMode();
            return;
        }
        String pw = txtAPPassword.getText();
        String status = txtAPStatus.getText();
        
        if(pw.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out all fields", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        userAccount.setPassword(pw);
        userAccount.setStatus(editMode);
        userAccount.setLastActivity(java.time.LocalDateTime.now().toString());
        userAccount.setLastUpdated(java.time.LocalDateTime.now().toString());
        
        JOptionPane.showMessageDialog(this, "Successfully updated", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        populateFields();
        setViewMode();
 
    }//GEN-LAST:event_btnAPUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAPBack;
    private javax.swing.JButton btnAPUpdate;
    private javax.swing.JLabel lblAPLastAcitivity;
    private javax.swing.JLabel lblAPLastUpdated;
    private javax.swing.JLabel lblAPPassword;
    private javax.swing.JLabel lblAPRole;
    private javax.swing.JLabel lblAPStatus;
    private javax.swing.JLabel lblAPUserName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAPLastActivity;
    private javax.swing.JTextField txtAPLastUpdated;
    private javax.swing.JTextField txtAPPassword;
    private javax.swing.JTextField txtAPRole;
    private javax.swing.JTextField txtAPStatus;
    private javax.swing.JTextField txtAPUserName;
    // End of variables declaration//GEN-END:variables

    private void setViewMode() {
        editMode = false;
        
        txtAPLastActivity.setEnabled(false);
        txtAPLastUpdated.setEditable(false);
        txtAPUserName.setEnabled(false);
        txtAPRole.setEnabled(false);
        
        txtAPPassword.setEnabled(false);
        txtAPStatus.setEnabled(false);

        btnAPUpdate.setText("Update");
}

    private void setEditMode() {
        editMode = true;

    // 수정 가능한 것만 열기
        txtAPPassword.setEnabled(true);
        txtAPStatus.setEnabled(true);

        btnAPUpdate.setText("Save");
    }


}
