/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ManageTheBusiness;

import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.OrderManagement.Order;
import TheBusiness.OrderManagement.OrderItem;
import TheBusiness.ProductManagement.Product;
import TheBusiness.ProductManagement.ProductCatalog;
import TheBusiness.Supplier.Supplier;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hyungs
 */
public class ReportViewerJPanel extends javax.swing.JPanel {
    
    JPanel CardSequencePanel;
    Business business;
    

    /**
     * Creates new form ReportViewerJPanel
     */
    public ReportViewerJPanel(JPanel CardSequencePanel,Business business) {
        initComponents();
        
        this.CardSequencePanel = CardSequencePanel;
        this.business = business;

        cmbReport.removeAllItems();
        cmbReport.addItem("Most Expensive Products");
        cmbReport.addItem("Most Valuable Customers");
        cmbReport.addItem("Supplier Summary");
        
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectReport = new javax.swing.JLabel();
        cmbReport = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Performance Report");

        lblSelectReport.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSelectReport.setText("Select Report: ");

        cmbReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Most Expensive Products", "Most Valuable Customers", "Supplier Summary", " " }));
        cmbReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbReportActionPerformed(evt);
            }
        });

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSelectReport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBack))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectReport)
                    .addComponent(cmbReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbReportActionPerformed
        // TODO add your handling code here:
        
        refreshTable();
    }//GEN-LAST:event_cmbReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelectReport;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        
        String selectedReport = String.valueOf(cmbReport.getSelectedItem()); //Extract the report by selecting item in combobox
        
        if (selectedReport.equals("Most Expensive Products")) {
            populateMostExpensiveProductsTable();
        }
        else if (selectedReport.equals("Most Valuable Customers")) {
            populateMostValuableCustomersTable();
        }
        else if (selectedReport.equals("Supplier Summary")) {
            populateSupplierSummaryTable();
        }
    }

    private void populateMostExpensiveProductsTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblReport.getModel();
        // Clear JTable
        model.setRowCount(0);
        model.setColumnCount(0);
        
        // Create Column
        model.addColumn("Product Name");
        model.addColumn("Supplier Name"); 
        model.addColumn("Product Price");
        
        ArrayList<Object[]> rows = new ArrayList<>();
        
        // Validate supplier information
        for (Supplier supplier : business.getSupplierDirectory().getSuplierList()) {
            
            ProductCatalog productcatalog = supplier.getProductCatalog();
            
            // Retrieve products from all suppliers
            for (Product product : productcatalog.getProductList()) {
                
                Object[] row = new Object[3];
                row[0] = product.toString();
                row[1] = supplier.getName();
                row[2] = product.getCeilingPrice(); // Most expensive products based in ceiling price
                
                rows.add(row);
            }
        }
        // Sort product by price(highest to lowest)
        rows.sort((row1,row2) -> Integer.compare((Integer) row2[2], (Integer) row1[2]));
        
        for (Object[] row : rows) {
            model.addRow(row);
        }
    }

    private void populateMostValuableCustomersTable() {
        DefaultTableModel model = (DefaultTableModel) tblReport.getModel();
        // Clear JTable
        model.setRowCount(0);
        model.setColumnCount(0);
        
        model.addColumn("Customer Name");
        model.addColumn("Total Sales");
        
        ArrayList<Object[]> rows = new ArrayList<>();
        
        for (CustomerProfile customer : business.getCustomerDirectory().getCustomerList()) {
            
            int totalSales = 0;
            
            for (Order order : business.getMasterOrderList().getOrders()) {
                
                if (order.getCustomer() == customer) {
                    totalSales += order.getOrderTotal();
                }
            }
            
            Object[] row = new Object [2];
            row[0] = customer.toString();
            row[1] = totalSales;
            
            rows.add(row);
        }
        rows.sort((row1,row2) -> Integer.compare((Integer) row2[1], (Integer) row1[1]));
        
        for (Object[] row : rows) {
            model.addRow(row);  
    }
}
        

    private void populateSupplierSummaryTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblReport.getModel();
        // Clear JTable
        model.setRowCount(0);
        model.setColumnCount(0);
        
        model.addColumn("Supplier Name");
        model.addColumn("Total Sales");
        model.addColumn("Loyalty Score");
        model.addColumn("Average Spending per Customer");
        model.addColumn("Top 5 Sales Score");
        
        ArrayList<Object[]> rows = new ArrayList<>();
        
        for (Supplier supplier : business.getSupplierDirectory().getSuplierList()) {
            
            int totalSales = 0;
            
            java.util.HashMap<TheBusiness.CustomerManagement.CustomerProfile, Integer> customerSalesMap = new java.util.HashMap<>();
            
            for (Order order : business.getMasterOrderList().getOrders()) {
                
                for (OrderItem oi : order.getOrderitems()) {
                    
                    Product product = oi.getSelectedProduct();
                    
                    if (supplier.getProductCatalog().getProductList().contains(product)) {
                        
                        int itemTotal = oi.getOrderItemTotal();
                        totalSales += itemTotal;
                        
                        CustomerProfile customer = order.getCustomer();
                        
                        if (customerSalesMap.containsKey(customer)) {
                            customerSalesMap.put(customer, customerSalesMap.get(customer) + itemTotal);
                        
                        }else {
                            customerSalesMap.put(customer, itemTotal);
                        }
                    }
                }
            }
            
            int distinctCustomers = customerSalesMap.size();
            
            double loyaltyScore = 0.0;
            double averageSpending = 0.0;
            double top5SalesScore = 0.0;
            
            int totalCustomerCount = business.getCustomerDirectory().getCustomerList().size();
            
            if (totalCustomerCount > 0) {
                loyaltyScore = (double) distinctCustomers/ totalCustomerCount;
            }
            
            if (distinctCustomers > 0) {
                averageSpending = (double) totalSales/distinctCustomers;
            }
            
            ArrayList<Integer> salesList = new ArrayList<>(customerSalesMap.values());
            java.util.Collections.sort(salesList, java.util.Collections.reverseOrder());
            
            int top5Total = 0;
            for (int i = 0; i < salesList.size() && i<5; i++) {
                top5Total += salesList.get(1);
            }
            
            if (top5Total > 0 && totalSales > 0) {
                top5SalesScore = (double) top5Total / totalSales;
            }
            
            Object[] row = new Object[5];
            row[0] = supplier.getName();
            row[1] = totalSales;
            row[2] = String.format("%.2f", loyaltyScore);
            row[3] = String.format("%.2f", averageSpending);
            row[4] = String.format("%.2f", top5SalesScore);
            
            rows.add(row);
        }
        
        rows.sort((row1,row2) -> Double.compare(Double.parseDouble((String) row2[2]), Double.parseDouble((String)row1[2])));
        
            for (Object[] row : rows) {
               model.addRow(row);  
    }
    }
}
