/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ManageTheBusiness;

import TheBusiness.Business.Business;
import javax.swing.JPanel;

/**
 *
 * @author Hyungs
 */
public class ReportViewerJPanel extends javax.swing.JPanel {
    
    JPanel CardSequencePanel;
    Business business;

    /**
     * Creates new form ReportViewerJPanel
     */
    public ReportViewerJPanel(JPanel CardSequencePanel,Business business) {
        initComponents();
        
        this.CardSequencePanel = CardSequencePanel;
        this.business = business;
        
        cmbReport.removeAllItems();
        cmbReport.addItem("Most Expensive Products");
        cmbReport.addItem("Most Valuable Customers");
        cmbReport.addItem("Supplier Summary");
        
        refreshTable();

    }
    
    private void cmbReportActionPerformed(java.awt.event.ActionEvent evt) {
        refreshTable();
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectReport = new javax.swing.JLabel();
        cmbReport = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Performance Report");

        lblSelectReport.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSelectReport.setText("Select Report: ");

        cmbReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Most Expensive Products", "Most Valuable Customers", "Supplier Summary", " " }));

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        btnBack.setText("<<< Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSelectReport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBack))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectReport)
                    .addComponent(cmbReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelectReport;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        
        String selectedReport = String.valueOf(cmbReport.getSelectedItem()); //Extract the report by selecting item in combobox
        
        if (selectedReport.equals("Most Expensive Products")) {
            populateMostExpensiveProductsTable();
        }
        else if (selectedReport.equals("Most Valuable Customers")) {
            populateMostValuableCustomersTable();
        }
        else if (selectedReport.equals("Supplier Summary")) {
            populateSupplierSummaryTable();
        }
    }

    private void populateMostExpensiveProductsTable() {
        
    }

    private void populateMostValuableCustomersTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void populateSupplierSummaryTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
