/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.StudentDirectory;


import javax.swing.JPanel;

import javax.swing.JOptionPane;
import java.awt.CardLayout;
import java.awt.Component; 
import java.util.Arrays;

/**
 *h
 * @author hdIV
 */

public class AdminUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    UserAccount userAccount; 
    boolean isEditMode;

    public AdminUserAccount(Business bz, JPanel jp, UserAccount ua) {

        CardSequencePanel = jp;
        this.business = bz;
        this.userAccount = ua;
        this.isEditMode = (ua != null);
        
        initComponents();
        addPersonSelectionListener(); // Add listener to determine role automatically
        populateFields(); // Populate fields based on mode

    }
    
    private void populateFields() {
        // Possible roles (reference)
        String[] possibleRoles = {"Admin", "Student", "Faculty", "Register"}; 

        if (userAccount != null) {
           //--Edit--
           
            if(txtId != null) { // Show Person Info field
                txtId.setVisible(true);
                txtId.setText(userAccount.getAssociatedPerson() != null ?
                                    userAccount.getAssociatedPerson().toString() : "N/A");
            }

            if(txtUsername != null) txtUsername.setText(userAccount.getUserLoginName());
           

            if(txtPassword != null) txtPassword.setText(""); // Still clear for security
            if(txtConfirmPassword != null) txtConfirmPassword.setText(""); // Clear confirmation field too
            if(lblPassword != null) lblPassword.setText("New Password (blank = no change):");
            // This will keep  password fields visible as requested
            if(lblConfirmPassword != null) lblConfirmPassword.setVisible(true);
            if(txtConfirmPassword != null) txtConfirmPassword.setVisible(true);

           

        } else {
            
            if(txtId != null) txtId.setVisible(false); // Hide Person Info field

        }
    }
    
    private void determineAndSetRole(Person person) {
       // ... (determineAndSetRole logic remains the same) ...
        String determinedRole = "N/A";
        if (person != null) {
            Department department = business.getDepartment();
            StudentDirectory sd = (department != null) ? department.getStudentDirectory() : null;
            FacultyDirectory fd = (department != null) ? department.getFacultyDirectory() : null;
            if (sd != null && sd.findStudent(person.getPersonId()) != null) determinedRole = "Student";
            else if (fd != null && fd.findFacultyByPersonId(person.getPersonId()) != null) determinedRole = "Faculty";
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        Back1 = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Administer User Account");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 550, 28);

        Back1.setText("<< Back");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        add(Back1);
        Back1.setBounds(40, 290, 100, 23);

        lblUsername.setText("Username");
        add(lblUsername);
        lblUsername.setBounds(20, 60, 100, 17);

        lblPassword.setText("Password");
        add(lblPassword);
        lblPassword.setBounds(20, 90, 100, 17);

        lblConfirmPassword.setText("ConfirmPassword");
        add(lblConfirmPassword);
        lblConfirmPassword.setBounds(20, 120, 110, 17);
        add(txtUsername);
        txtUsername.setBounds(140, 60, 140, 23);
        add(txtPassword);
        txtPassword.setBounds(140, 90, 140, 23);
        add(txtConfirmPassword);
        txtConfirmPassword.setBounds(140, 120, 140, 23);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(270, 210, 72, 23);

        jLabel1.setText("ID");
        add(jLabel1);
        jLabel1.setBounds(400, 60, 20, 17);
        add(txtId);
        txtId.setBounds(430, 60, 150, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed

        // Navigate back to the ManagePersonsJPanel
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
        refreshPreviousTable();
    }//GEN-LAST:event_Back1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // 1. Get Input
        String username = (txtUsername != null) ? txtUsername.getText().trim() : "";
        String password = (txtPassword != null) ? txtPassword.getText() : "";
        String confirmPassword = (txtConfirmPassword != null) ? txtConfirmPassword.getText() : "";
        Person selectedPerson = null;
        }

        // 2. Validation
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username cannot be empty and a valid Role must be determined for the selected Person.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; // Stay on page
        }
        // Password required only for new accounts
        if (!isEditMode && password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password cannot be empty for new accounts.", "Input Error", JOptionPane.ERROR_MESSAGE);
             return; // Stay on page
        }
         // Password match check needed if password field is not empty (allows no change in edit mode)
         if (!password.isEmpty() && !password.equals(confirmPassword)) {
             JOptionPane.showMessageDialog(this, "Passwords do not match.", "Input Error", JOptionPane.ERROR_MESSAGE);
             return; // Stay on page
         }
         // Password policy check (only if password is not empty)
         if (!password.isEmpty() && password.length() < 4) {
             JOptionPane.showMessageDialog(this, "Password must be at least 4 characters long.", "Input Error", JOptionPane.ERROR_MESSAGE);
              return; // Stay on page
         }


        UserAccountDirectory uad = business.getUserAccountDirectory();
        if (uad == null) {
             JOptionPane.showMessageDialog(this, "Error: User Account Directory not found.", "Internal Error", JOptionPane.ERROR_MESSAGE);
            return; // Stay on page
        }


        // Check username uniqueness
        UserAccount existingAccountWithUsername = uad.findUserAccount(username);
        if (existingAccountWithUsername != null && (!isEditMode || !existingAccountWithUsername.getUserLoginName().equalsIgnoreCase(userAccount.getUserLoginName()))) {
             JOptionPane.showMessageDialog(this, "This username is already taken.", "Validation Error", JOptionPane.ERROR_MESSAGE);
             return; // Stay on page
        }

        boolean saveSuccessful = false;
        if (isEditMode) {
            // --- Update ---
            if (userAccount == null) { /* Error */ return; }

            // Update password ONLY if a new one was entered
            if (!password.isEmpty()) {
                 // !!! IMPORTANT: Need UserAccount.setPassword(String) method !!!
                 // accountToEdit.setPassword(password); // Implement password setting securely
                 System.out.println("Placeholder: Password would be updated for " + userAccount.getUserLoginName());
            } else {
                 System.out.println("Password field empty, password not changed for " + userAccount.getUserLoginName());
            }


             // Update role (verify - role shouldn't change here typically)
             // !!! IMPORTANT: Need UserAccount.setRole(String) method !!!
              accountToEdit.setRole(determinedRole); // Usually role is fixed or changed via profile management
              System.out.println("Placeholder: Role (" + determinedRole + ") verified for " + userAccount.getUserLoginName());

             JOptionPane.showMessageDialog(this, "User account updated successfully.", "Update Success", JOptionPane.INFORMATION_MESSAGE);
             saveSuccessful = true;

        } else {
            // --- Create ---
             if (selectedPerson == null) {
                 JOptionPane.showMessageDialog(this, "Please select a Person to associate the account with.", "Input Error", JOptionPane.ERROR_MESSAGE);
                 return; // Stay on page
              }

            // Create new UserAccount using the determined role
            UserAccount newUserAccount = uad.newUserAccount(selectedPerson, username, password, Role);

            if (newUserAccount != null) {
                 JOptionPane.showMessageDialog(this, "User account created successfully for " + selectedPerson.getName() + " with role " + Role + ".", "Creation Success", JOptionPane.INFORMATION_MESSAGE);
                 saveSuccessful = true;
            } else {
                 JOptionPane.showMessageDialog(this, "Failed to create user account (check directory implementation).", "Creation Error", JOptionPane.ERROR_MESSAGE);
                 saveSuccessful = false; // Stay on page
            }
        }

        // Navigate back only on success
        if (saveSuccessful) {
            CardSequencePanel.remove(this);
            ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
            refreshPreviousTable();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Helper to securely clear password arrays
    private void clearPasswordArrays(char[]... arrays) {
       // ... (clearPasswordArrays logic remains the same) ...
        for (char[] array : arrays) { if (array != null) Arrays.fill(array, ' '); }
    }
    
    // Helper method to find and refresh the ManageUserAccountsJPanel table
    private void refreshPreviousTable() {
        // ... (refreshPreviousTable logic remains the same) ...
        Component[] components = CardSequencePanel.getComponents();
        for (int i = components.length - 1; i >= 0; i--) {
            if (components[i] instanceof ManageUserAccountsJPanel) {
                ((ManageUserAccountsJPanel) components[i]).refreshTable();
                return;
            }
        }
        System.err.println("Warning: Could not find ManageUserAccountsJPanel in CardSequencePanel to refresh.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtConfirmPassword;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
