/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.Persona.Transcript;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumayyahhusain
 */
public class CourseRegistrationJPanel extends javax.swing.JPanel {

    Business business;
    StudentProfile studentProfile;
    JPanel CardSequencePanel;
    
    private static final String CURRENT_SEMESTER = "Spring 2026";
    
    /**
     * Creates new form CourseRegistrationJPanel
     */
    public CourseRegistrationJPanel(Business business, StudentProfile studentProfile, JPanel CardSequencePanel) {
        this.studentProfile = studentProfile;
        this.CardSequencePanel = CardSequencePanel;
        initComponents();
        
        populateSearchComboBox();
        populateAvailableCoursesTable();
        populateMyCoursesTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourseRegistrationTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        cmbSearchType = new javax.swing.JComboBox<>();
        fieldSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailableCourses = new javax.swing.JTable();
        lblAvailableCourses = new javax.swing.JLabel();
        btnEnroll = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMyCourses = new javax.swing.JTable();
        lblMyCourses = new javax.swing.JLabel();
        btnDrop = new javax.swing.JButton();

        lblCourseRegistrationTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblCourseRegistrationTitle.setText("Course Registration");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblSearch.setText("Search:");

        cmbSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblAvailableCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Title", "Instructor", "Credits", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblAvailableCourses);

        lblAvailableCourses.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAvailableCourses.setText("Available Courses - Spring 2026");

        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        tblMyCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Title", "Instructor", "Credits"
            }
        ));
        jScrollPane2.setViewportView(tblMyCourses);

        lblMyCourses.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblMyCourses.setText("My Courses - Spring 2026");

        btnDrop.setText("Drop");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMyCourses)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblAvailableCourses)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addGap(190, 190, 190)
                            .addComponent(lblCourseRegistrationTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSearch)
                            .addGap(18, 18, 18)
                            .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)
                        .addComponent(btnEnroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2))
                    .addComponent(btnDrop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseRegistrationTitle)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(19, 19, 19)
                .addComponent(lblAvailableCourses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMyCourses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDrop)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMyCourses.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,"Please select a course to drop!","No Selection",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {

            String courseId = (String) tblMyCourses.getValueAt(selectedRow, 0);
            String courseName = (String) tblMyCourses.getValueAt(selectedRow, 1);
            

            int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to drop:\n" + courseId + " - " + courseName + "?","Confirm Drop",JOptionPane.YES_NO_OPTION);
            
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }
            
            JOptionPane.showMessageDialog(this,"Successfully dropped " + courseId,"Drop Success",JOptionPane.INFORMATION_MESSAGE);
                
            populateAvailableCoursesTable();
            populateMyCoursesTable();

            
        } catch (Exception e) {
            System.err.println("Error dropping course: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();
        StudentWorkAreaJPanel studentPanel = new StudentWorkAreaJPanel(business, studentProfile, CardSequencePanel);
        CardSequencePanel.add("student", studentPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void fieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSearchActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAvailableCourses.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,"Please select a course to enroll!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            String courseId = (String) tblAvailableCourses.getValueAt(selectedRow, 0);
            String courseName = (String) tblAvailableCourses.getValueAt(selectedRow, 1);
            int credits = (int) tblAvailableCourses.getValueAt(selectedRow, 3);
            String status = (String) tblAvailableCourses.getValueAt(selectedRow, 5);
            

            if (status.equals("Full")) {
                JOptionPane.showMessageDialog(this,"This course is full!","Enrollment Failed",JOptionPane.ERROR_MESSAGE);
                return;
            } else {
 
            JOptionPane.showMessageDialog(this,"Successfully enrolled in " + courseId + " - " + courseName,"Success",JOptionPane.INFORMATION_MESSAGE);
            
               
            populateAvailableCoursesTable();
            populateMyCoursesTable();
            }
            
        } catch (Exception e) {
            System.err.println("Error enrolling: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error: " + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchType = (String) cmbSearchType.getSelectedItem();
        String searchText = fieldSearch.getText().trim();
        
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter search text!", 
                "Search Error", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblAvailableCourses.getModel();
        model.setRowCount(0);
        
        try {
            Department dept = business.getDepartment();
            CourseSchedule schedule = dept.getCourseSchedule(CURRENT_SEMESTER);
            
            if (schedule == null) return;
            
            ArrayList<CourseOffer> offers = schedule.getSchedule();
            int foundCount = 0;
            
            for (CourseOffer offer : offers) {
                boolean matches = false;
                
                Course course = offer.getSubjectCourse();
                FacultyProfile faculty = offer.getFacultyProfile();

                if (searchType.equals("Course ID")) {
                    matches = course.getCourseNumber().toLowerCase().contains(searchText.toLowerCase());
                    
                } else if (searchType.equals("Teacher")) {
                    if (faculty != null) {
                        String teacherName = faculty.getPerson().getFirstName();
                        matches = teacherName.toLowerCase().contains(searchText.toLowerCase());
                    }
                    
                } else if (searchType.equals("Course Name")) {
                    matches = course.getCourseName().toLowerCase().contains(searchText.toLowerCase());
                }

                
                if (matches) {
                    String courseId = course.getCourseNumber();
                    String courseName = course.getCourseName();
                    String instructor = faculty != null ? faculty.getPerson().getFirstName() : "TBA";
                    int credits = course.getCredits();
                    
                    int totalSeats = offer.getSeatCount();
                    int occupiedSeats = offer.getEnrolledCount();
                    int availableSeats = totalSeats - occupiedSeats;
                    String status = availableSeats > 0 ? "Open" : "Full";
                    
                    Object[] row = {
                        courseId,
                        courseName,
                        instructor,
                        credits,
                        availableSeats + "/" + totalSeats,
                        status
                    };
                    
                    model.addRow(row);
                    foundCount++;
                }
            }
            
            if (foundCount == 0) {
                JOptionPane.showMessageDialog(this,
                    "No courses found matching: " + searchText,
                    "Search Result",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                System.out.println("Found " + foundCount + " courses");
            }
            
        } catch (Exception e) {
            System.err.println("Error searching courses: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbSearchType;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvailableCourses;
    private javax.swing.JLabel lblCourseRegistrationTitle;
    private javax.swing.JLabel lblMyCourses;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblAvailableCourses;
    private javax.swing.JTable tblMyCourses;
    // End of variables declaration//GEN-END:variables

    private void populateSearchComboBox() {
        cmbSearchType.removeAllItems();
        cmbSearchType.addItem("Course ID");
        cmbSearchType.addItem("Teacher");
        cmbSearchType.addItem("Course Name");
    }

    private void populateAvailableCoursesTable() {
        DefaultTableModel model = (DefaultTableModel) tblAvailableCourses.getModel();
        model.setRowCount(0);
        
        try {
            Department dept = business.getDepartment();
            CourseSchedule schedule = dept.getCourseSchedule(CURRENT_SEMESTER);
            
            if (schedule == null) {
                System.out.println("No course schedule found for " + CURRENT_SEMESTER);
                return;
            }
            
            ArrayList<CourseOffer> offers = schedule.getSchedule();
            
            if (offers == null || offers.isEmpty()) {
                System.out.println("No course offers available");
                return;
            }
            
            
            for (CourseOffer offer : offers) {
                Course course = offer.getSubjectCourse();
                FacultyProfile faculty = offer.getFacultyProfile();
                
                String courseId = course.getCourseNumber();
                String courseName = course.getCourseName();
                String instructorFirstName = faculty != null ? faculty.getPerson().getFirstName() : "TBA";
                //String instructorLastName = faculty != null ? faculty.getPerson().getLastName() : "TBA";
                int credits = course.getCredits();
                
                
                int totalSeats = offer.getSeatCount();
                int occupiedSeats = offer.getEnrolledCount();
                int availableSeats = totalSeats - occupiedSeats;
                
                String status = availableSeats > 0 ? "Open" : "Full";
                
                Object[] row = {
                    courseId,
                    courseName,
                    instructorFirstName, //+ instructorLastName,
                    credits,
                    //availableSeats + "/" + totalSeats,
                    //"open"
                };
                
                model.addRow(row);
            }
            
            System.out.println("Loaded " + offers.size() + " available courses");
            
        } catch (Exception e) {
            System.err.println("Error loading available courses: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void populateMyCoursesTable() {
        DefaultTableModel model = (DefaultTableModel) tblMyCourses.getModel();
        model.setRowCount(0);
        
        try {
            Transcript transcript = studentProfile.getTranscript();
            CourseLoad courseLoad = transcript.getCourseLoadBySemester(CURRENT_SEMESTER);
            
            if (courseLoad == null) {
                System.out.println("No course load for current semester");
                return;
            }
            
            ArrayList<SeatAssignment> seats = courseLoad.getSeatAssignments();
            
            if (seats == null || seats.isEmpty()) {
                System.out.println("No courses enrolled");
                return;
            }
            
            for (SeatAssignment seat : seats) {
                Course course = seat.getAssociatedCourse();
                CourseOffer offer = seat.getCourseOffer();
                FacultyProfile faculty = offer.getFacultyProfile();
                
                String courseId = course.getCourseNumber();
                String courseName = course.getCourseName();
                String instructor = faculty != null ? faculty.getPerson().getFirstName() : "TBA";
                int credits = course.getCredits();
                
                Object[] row = {
                    courseId,
                    courseName,
                    instructor,
                    credits
                };
                
                model.addRow(row);
            }
            
            System.out.println("Loaded " + seats.size() + " enrolled courses");
            
        } catch (Exception e) {
            System.err.println("Error loading my courses: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    
}
