/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp02;

import Business.Business;
import Business.UserAccounts.UserAccount;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.Seat;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyAssignment;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hyungs
 */
public class PerformanceReportJPanel extends javax.swing.JPanel {
    
    Business business;
    FacultyProfile facultyProfile;
    JPanel CardSequencePanel;
    Department department;
   
    
    /**
     * Creates new form PerformanceReportJPanel
     */
    public PerformanceReportJPanel(Business business,FacultyProfile facultyProfile, JPanel CardSequencePanel ) {
        initComponents();
        
        this.business = business;
        this.facultyProfile = facultyProfile;
        this.CardSequencePanel = CardSequencePanel;

        this.department = business.getDepartment();
        
        populateCourseCombo();
        populateSemesterCombo();
        
        DefaultTableModel model = (DefaultTableModel) tblPerformanceReports.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox<>();
        btnGenerate = new javax.swing.JButton();
        lblCourse = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerformanceReports = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblTitle.setText("Performance Reports");

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Application Engineering", "Agile Software Development", "Business Processing Engineering", "Software Quality Control and Management", "Planning and Managing Information System" }));
        cmbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourseActionPerformed(evt);
            }
        });

        btnGenerate.setText("Generate ");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        lblCourse.setText("Course:");

        lblSemester.setText("Semester");

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Spring2026" }));

        tblPerformanceReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUID", "Student Name", "Degree", "GPA", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblPerformanceReports);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnView.setText("View Student Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 112, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(lblSemester)
                                .addGap(18, 18, 18)
                                .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGenerate)
                                .addGap(131, 131, 131))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addGap(301, 301, 301))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerate)
                    .addComponent(lblCourse)
                    .addComponent(lblSemester)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnView))
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.show(CardSequencePanel, "faculty");
        
        CardSequencePanel.remove(this);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblPerformanceReports.getModel();
        model.setRowCount(0);
        
        if (department == null) return;
        if (cmbCourse.getSelectedItem() == null) return;
        if (cmbSemester.getSelectedItem() == null) return;
        
        String courseNumber = (String) cmbCourse.getSelectedItem();
        String semester = (String) cmbSemester.getSelectedItem();

        //semester
        CourseSchedule cs = department.getCourseSchedule(semester);
        if (cs == null) {
            JOptionPane.showMessageDialog(null, "No Course Schedule for " + semester, "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //enrolled students only (SeatAssignment list)
        CourseOffer co = cs.getCourseOfferByNumber(courseNumber);
        if (co == null) {
            JOptionPane.showMessageDialog(null, "Course not offered this semester", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        for (Seat s : co.getSeatList()) {
            if (s == null) continue;
            if (!s.isOccupied()) continue;
            
            SeatAssignment sa = s.getSeatAssignment();
            if (sa == null) continue;
            
            StudentProfile sp = sa.getStudentProfile();
            if (sp == null || sp.getPerson() == null) continue;
            
            Person p = sp.getPerson();
            
            Object row[] = new Object[5];
            row[0] = sp;
            row[1] = p.getFirstName() + "" + p.getLastName();
            row[2] = p.getDegree();
            row[3] = p.getGPA();
            row[4] = (p.getGPA() >= 3.0) ? "Good Standing" : "Failed";
            
            model.addRow(row);
            

        }
        

        
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPerformanceReports.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a student row first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        StudentProfile sp = (StudentProfile) tblPerformanceReports.getValueAt(selectedRow, 0);
        
        Department dept = business.getDepartment();
        
        StudentProfileDetailJPanel panel = new StudentProfileDetailJPanel (business, sp,CardSequencePanel);
        CardSequencePanel.add("StudentDetail", panel);
        
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.show(CardSequencePanel, "StudentDetail");
        
                
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblPerformanceReports;
    // End of variables declaration//GEN-END:variables

    private void populateCourseCombo() {
        cmbCourse.removeAllItems();
        
        if (facultyProfile == null) return;
        
        for (FacultyAssignment fa : facultyProfile.getFacultyAssignments()) {
            if (fa == null || fa.getCourseOffer() == null) continue;
            CourseOffer co = fa.getCourseOffer();
            if (co.getCourse() == null) continue;
            
            cmbCourse.addItem(co.getCourse().getCourseNumber());
        }
    }

    private void populateSemesterCombo() {
        cmbSemester.removeAllItems();
        
        if (department != null && department.getMasterCourseCatalog() != null && !department.getMasterCourseCatalog().isEmpty()) {
            for (String sem : department.getMasterCourseCatalog().keySet()) {
                cmbSemester.addItem(sem);
            }
        } else{
            cmbSemester.addItem("Spring 2026"); // fallback
        }
    }
}
