/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.WorkAreaFacultyRole;

import Business.Business;
import javax.swing.JPanel;

/**
 *
 * @author Hyungs
 */
public class FacultyWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel workAreaJPanel;
    Business business;

    /**
     * Creates new form FacultyWorkAreaJPanel
     */
    public FacultyWorkAreaJPanel(Business b, JPanel workArea) {
        initComponents();
        
        this.business = b;
        this.workAreaJPanel = workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnFacultyManageCourse = new javax.swing.JButton();
        btnFacultyProfile = new javax.swing.JButton();
        btnFacultyStudentProfile = new javax.swing.JButton();
        btnFacultyPerformReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setText("My Faculty Profile");

        btnFacultyManageCourse.setBackground(new java.awt.Color(102, 153, 255));
        btnFacultyManageCourse.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnFacultyManageCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnFacultyManageCourse.setText("Manage Course");
        btnFacultyManageCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFacultyProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnFacultyProfile.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnFacultyProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnFacultyProfile.setText("My Profile");
        btnFacultyProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFacultyStudentProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnFacultyStudentProfile.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnFacultyStudentProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnFacultyStudentProfile.setText("Manage Student Profile");
        btnFacultyStudentProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFacultyPerformReport.setBackground(new java.awt.Color(102, 153, 255));
        btnFacultyPerformReport.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnFacultyPerformReport.setForeground(new java.awt.Color(255, 255, 255));
        btnFacultyPerformReport.setText("Performance Report");
        btnFacultyPerformReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFacultyProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(btnFacultyManageCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFacultyStudentProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(btnFacultyPerformReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFacultyStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacultyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFacultyPerformReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacultyManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(419, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFacultyManageCourse;
    private javax.swing.JButton btnFacultyPerformReport;
    private javax.swing.JButton btnFacultyProfile;
    private javax.swing.JButton btnFacultyStudentProfile;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
