/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.WorkArea.FacultyRole.FacultyRoleWorkResp;

import Business.Business;
import Business.Profile.FacultyProfile;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hyungs
 */
public class FacultyManagePersonJPanel extends javax.swing.JPanel {
    
    JPanel workAreaJPanel;
    Business business;
    UserAccount userAccount;

    /**
     * Creates new form FacultyManagePersonJPanel
     */
    public FacultyManagePersonJPanel(Business b, JPanel workArea, UserAccount ua) {
        initComponents();
        this.workAreaJPanel = workArea;
        this.business = b;
        this.userAccount = ua;
        
        populateFields();
        setViewMode();
    }
       
    private void populateFields() {
        FacultyProfile fp = (FacultyProfile) userAccount.getAssociatedPersonProfile();
        
        txtFacultyName.setText(fp.getName());
        txtFacultyUserName.setText(userAccount.getUserLoginName());
        txtFacultyRole.setText(fp.getRole());
        txtFacultyDepartment.setText(fp.getDepartment());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFacultyName = new javax.swing.JLabel();
        lblFacultyUserName = new javax.swing.JLabel();
        lblFacultyDepartment = new javax.swing.JLabel();
        lblFacultyRole = new javax.swing.JLabel();
        txtFacultyName = new javax.swing.JTextField();
        txtFacultyUserName = new javax.swing.JTextField();
        txtFacultyDepartment = new javax.swing.JTextField();
        txtFacultyRole = new javax.swing.JTextField();
        btnFacultyBack = new javax.swing.JButton();
        btnFacultyUpdate = new javax.swing.JButton();
        btnFacultySave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setText("My Profile");

        lblFacultyName.setText("Faculty Name :");

        lblFacultyUserName.setText("User Name:");

        lblFacultyDepartment.setText("Department : ");

        lblFacultyRole.setText("Role: ");

        btnFacultyBack.setText("<<< Back");
        btnFacultyBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyBackActionPerformed(evt);
            }
        });

        btnFacultyUpdate.setText("Update");
        btnFacultyUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyUpdateActionPerformed(evt);
            }
        });

        btnFacultySave.setText("Save");
        btnFacultySave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultySaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFacultyBack)
                        .addGap(170, 170, 170)
                        .addComponent(lblTitle))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(btnFacultySave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFacultyUpdate))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(187, 187, 187)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblFacultyUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFacultyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFacultyRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFacultyDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFacultyUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFacultyDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFacultyRole, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnFacultyBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFacultyName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyUserName)
                    .addComponent(txtFacultyUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyDepartment)
                    .addComponent(txtFacultyDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyRole)
                    .addComponent(txtFacultyRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFacultySave)
                    .addComponent(btnFacultyUpdate))
                .addContainerGap(356, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacultyBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyBackActionPerformed
        // TODO add your handling code here:
        workAreaJPanel.remove(this);
        
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
    }//GEN-LAST:event_btnFacultyBackActionPerformed

    private void btnFacultySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultySaveActionPerformed
        // TODO add your handling code here:
        String name = txtFacultyName.getText();
        String department = txtFacultyDepartment.getText();
        String role = txtFacultyRole.getText();
        String un = txtFacultyUserName.getText();
        
        if (name.isEmpty() || department.isEmpty() || role.isEmpty() || un.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out all required fields.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        FacultyProfile fp = (FacultyProfile) userAccount.getAssociatedPersonProfile();
        fp.setName(name);
        fp.setDepartment(department);
        
        userAccount.setLastUpdated(java.time.LocalDateTime.now().toString());
        
        JOptionPane.showMessageDialog(this, "Sucessfully saved.", "Infomration", JOptionPane.INFORMATION_MESSAGE);
        
        populateFields();
        setViewMode();
        
    }//GEN-LAST:event_btnFacultySaveActionPerformed

    private void btnFacultyUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnFacultyUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFacultyBack;
    private javax.swing.JButton btnFacultySave;
    private javax.swing.JButton btnFacultyUpdate;
    private javax.swing.JLabel lblFacultyDepartment;
    private javax.swing.JLabel lblFacultyName;
    private javax.swing.JLabel lblFacultyRole;
    private javax.swing.JLabel lblFacultyUserName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtFacultyDepartment;
    private javax.swing.JTextField txtFacultyName;
    private javax.swing.JTextField txtFacultyRole;
    private javax.swing.JTextField txtFacultyUserName;
    // End of variables declaration//GEN-END:variables

    private void setViewMode() {
         txtFacultyName.setEnabled(false);
    txtFacultyDepartment.setEnabled(false);
    txtFacultyUserName.setEnabled(false);
    txtFacultyRole.setEnabled(false);

    btnFacultySave.setEnabled(false);
    btnFacultyUpdate.setEnabled(true);
   }

private void setEditMode() {
    txtFacultyName.setEnabled(true);
    txtFacultyDepartment.setEnabled(true);

    txtFacultyUserName.setEnabled(false);
    txtFacultyRole.setEnabled(false);

    btnFacultySave.setEnabled(true);
    btnFacultyUpdate.setEnabled(false);
}

}
