/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.WorkArea.FacultyRole.FacultyRoleWorkResp;

import Business.Business;
import Business.Profile.FacultyProfile;
import Business.Profile.Profile;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hyungs
 */
public class ManageFacultyDirectoryJPanel extends javax.swing.JPanel {
    
    Business business;
    JPanel workAreaJPanel;
            

    /**
     * Creates new form ManageFacultyDirectoryJPanel
     */
    public ManageFacultyDirectoryJPanel(Business business, JPanel workArea) {
        initComponents();
        this.workAreaJPanel = workArea;
        this.business = business;
        
        populateTable();
    }
        
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblFacultyDirectory.getModel();
        model.setRowCount(0);
        
        UserAccountDirectory uad = business.getUserAccountDirectory();
        
        for (UserAccount ua : uad.getUserAccountList()) {
            Profile p = ua.getAssociatedPersonProfile();
            
            if (p instanceof FacultyProfile) {
                FacultyProfile fp = (FacultyProfile) p;
                
                Object [] row = new Object[4];
                row[0] = fp.getName();
                row[1] = ua;
                row[2] = fp.getDepartment();
                row[3] = ua.getLastUpdated();
                
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacultyDirectory = new javax.swing.JTable();
        btnFacultyDirectoryBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setText("Faculty Directory");

        tblFacultyDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "User Name", "Department", "Last Updated"
            }
        ));
        jScrollPane1.setViewportView(tblFacultyDirectory);

        btnFacultyDirectoryBack.setText("<<< Back");
        btnFacultyDirectoryBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyDirectoryBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnFacultyDirectoryBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(lblTitle)))
                        .addGap(0, 306, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnFacultyDirectoryBack)
                .addGap(33, 33, 33)
                .addComponent(lblTitle)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacultyDirectoryBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyDirectoryBackActionPerformed
        // TODO add your handling code here:
        workAreaJPanel.remove(this);
        CardLayout layout = (CardLayout)workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
        
    }//GEN-LAST:event_btnFacultyDirectoryBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFacultyDirectoryBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblFacultyDirectory;
    // End of variables declaration//GEN-END:variables


}
