/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author Hyungs
 */
public class LocaAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LocaAddressJPanel
     */
    Person product;
    public LocaAddressJPanel(Person p) {
        initComponents();
        product = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLocalAddress = new javax.swing.JLabel();
        lblLocalStreet = new javax.swing.JLabel();
        lblLocalUnit = new javax.swing.JLabel();
        lblLocalCity = new javax.swing.JLabel();
        lblLocalZip = new javax.swing.JLabel();
        lblLocalCountry = new javax.swing.JLabel();
        fieldLocalStreet = new javax.swing.JTextField();
        fieldLocalUnit = new javax.swing.JTextField();
        fieldLocalCity = new javax.swing.JTextField();
        fieldLocalZip = new javax.swing.JTextField();
        fieldLocalCountry = new javax.swing.JTextField();
        btnLocalSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblLocalAddress.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        lblLocalAddress.setText("Local Address Information");

        lblLocalStreet.setText("Street Name");

        lblLocalUnit.setText("Unit Number");

        lblLocalCity.setText("City");

        lblLocalZip.setText("Zip Code");

        lblLocalCountry.setText("Country");

        fieldLocalStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalStreetActionPerformed(evt);
            }
        });

        btnLocalSave.setText("Save");
        btnLocalSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLocalSave)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblLocalAddress))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLocalStreet)
                            .addComponent(lblLocalUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLocalCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLocalZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLocalCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldLocalZip, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldLocalCity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldLocalUnit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldLocalStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fieldLocalCountry))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLocalAddress)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLocalStreet)
                    .addComponent(fieldLocalStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalUnit)
                    .addComponent(fieldLocalUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalCity)
                    .addComponent(fieldLocalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalZip)
                    .addComponent(fieldLocalZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalCountry)
                    .addComponent(fieldLocalCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(btnLocalSave)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocalSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalSaveActionPerformed
        // TODO add your handling code here:
        String streetName = fieldLocalStreet.getText();
        String unitNumber = fieldLocalUnit.getText();
        String city = fieldLocalCity.getText();
        String zipCode = fieldLocalZip.getText();
        String country = fieldLocalCountry.getText();
        
        product.getLocalAddress().setLocalStreetName(streetName);
        product.getLocalAddress().setLocalUnitNum(unitNumber);
        product.getLocalAddress().setLocalCity(city);
        product.getLocalAddress().setLocalZipCode(zipCode);
        product.getLocalAddress().setLocalCountry(country);
        
        JOptionPane.showMessageDialog(this,"Successfully Saved!");
        
        fieldLocalStreet.setText("");
        fieldLocalUnit.setText("");
        fieldLocalCity.setText("");
        fieldLocalZip.setText("");
        fieldLocalCountry.setText("");

    }//GEN-LAST:event_btnLocalSaveActionPerformed

    private void fieldLocalStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalStreetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocalSave;
    private javax.swing.JTextField fieldLocalCity;
    private javax.swing.JTextField fieldLocalCountry;
    private javax.swing.JTextField fieldLocalStreet;
    private javax.swing.JTextField fieldLocalUnit;
    private javax.swing.JTextField fieldLocalZip;
    private javax.swing.JLabel lblLocalAddress;
    private javax.swing.JLabel lblLocalCity;
    private javax.swing.JLabel lblLocalCountry;
    private javax.swing.JLabel lblLocalStreet;
    private javax.swing.JLabel lblLocalUnit;
    private javax.swing.JLabel lblLocalZip;
    // End of variables declaration//GEN-END:variables
}
