/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;

/**
 *
 * @author Hyungs
 */
public class ViewBankJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewBankJPanel
     */
    Person product;
    public ViewBankJPanel(Person p) {
        initComponents();
        product = p;
        display();
    }
    
    private void display() {
        fieldAcctHldrName.setText(product.getBankAccount().getAccountHolderName());
        fieldBankName.setText(product.getBankAccount().getBankName());
        fieldAcctNum.setText(product.getBankAccount().getAccountNumber());
        fieldAcctType.setText(product.getBankAccount().getAccountType());
        fieldBalance.setText(String.valueOf(product.getBankAccount().getBalance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewBankTitle = new javax.swing.JLabel();
        lblViewAcctHldrName = new javax.swing.JLabel();
        lblViewBankName = new javax.swing.JLabel();
        lblViewAcctNum = new javax.swing.JLabel();
        lblViewAcctType = new javax.swing.JLabel();
        lblViewBalance = new javax.swing.JLabel();
        fieldAcctHldrName = new javax.swing.JTextField();
        fieldBankName = new javax.swing.JTextField();
        fieldAcctNum = new javax.swing.JTextField();
        fieldAcctType = new javax.swing.JTextField();
        fieldBalance = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        lblViewBankTitle.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        lblViewBankTitle.setText("Bank Information");

        lblViewAcctHldrName.setText("Account Holder Name");

        lblViewBankName.setText("Bank Name");

        lblViewAcctNum.setText("Account Number");

        lblViewAcctType.setText("Account Type");

        lblViewBalance.setText("Balance");

        fieldAcctHldrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAcctHldrNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewAcctHldrName)
                    .addComponent(lblViewBankName)
                    .addComponent(lblViewAcctNum)
                    .addComponent(lblViewAcctType)
                    .addComponent(lblViewBalance))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldAcctHldrName, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(fieldBankName)
                    .addComponent(fieldAcctNum)
                    .addComponent(fieldAcctType)
                    .addComponent(fieldBalance))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(lblViewBankTitle)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblViewBankTitle)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewAcctHldrName)
                    .addComponent(fieldAcctHldrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewBankName)
                    .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewAcctNum)
                    .addComponent(fieldAcctNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewAcctType)
                    .addComponent(fieldAcctType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewBalance)
                    .addComponent(fieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldAcctHldrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAcctHldrNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAcctHldrNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAcctHldrName;
    private javax.swing.JTextField fieldAcctNum;
    private javax.swing.JTextField fieldAcctType;
    private javax.swing.JTextField fieldBalance;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JLabel lblViewAcctHldrName;
    private javax.swing.JLabel lblViewAcctNum;
    private javax.swing.JLabel lblViewAcctType;
    private javax.swing.JLabel lblViewBalance;
    private javax.swing.JLabel lblViewBankName;
    private javax.swing.JLabel lblViewBankTitle;
    // End of variables declaration//GEN-END:variables

}
