/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;

/**
 *
 * @author Hyungs
 */
public class ViewHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewHomeJPanel
     */
    Person product;
    public ViewHomeJPanel(Person p) {
        initComponents();
        product = p;
        display();
    }
    
    private void display() {
        fieldViewHomeStreet.setText(product.getHomeAddress().getHomeStreetName());
        fieldViewHomeUnit.setText(product.getHomeAddress().getHomeUnitNum());
        fieldViewHomeCity.setText(product.getHomeAddress().getHomeCity());
        fieldViewHomeZip.setText(product.getHomeAddress().getHomeZipCode());
        fieldViewHomeCountry.setText(product.getHomeAddress().getHomeCountry());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewHomeTitle = new javax.swing.JLabel();
        lblViewHomeStreet = new javax.swing.JLabel();
        lblViewHomeUnit = new javax.swing.JLabel();
        lblViewHomeCity = new javax.swing.JLabel();
        lblViewHomeZip = new javax.swing.JLabel();
        lblViewHomeCountry = new javax.swing.JLabel();
        fieldViewHomeStreet = new javax.swing.JTextField();
        fieldViewHomeUnit = new javax.swing.JTextField();
        fieldViewHomeCity = new javax.swing.JTextField();
        fieldViewHomeZip = new javax.swing.JTextField();
        fieldViewHomeCountry = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        lblViewHomeTitle.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        lblViewHomeTitle.setText("Home Address Information");

        lblViewHomeStreet.setText("Street Name");

        lblViewHomeUnit.setText("Unit Number");

        lblViewHomeCity.setText("City");

        lblViewHomeZip.setText("Zip Code");

        lblViewHomeCountry.setText("Country");

        fieldViewHomeStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldViewHomeStreetActionPerformed(evt);
            }
        });

        fieldViewHomeCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldViewHomeCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblViewHomeCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblViewHomeZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblViewHomeCountry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblViewHomeUnit))
                    .addComponent(lblViewHomeStreet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fieldViewHomeZip, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(fieldViewHomeStreet, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldViewHomeUnit, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldViewHomeCity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldViewHomeCountry))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblViewHomeTitle)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewHomeTitle)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldViewHomeStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addComponent(fieldViewHomeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldViewHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldViewHomeZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldViewHomeCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblViewHomeStreet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblViewHomeUnit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblViewHomeCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblViewHomeZip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblViewHomeCountry)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldViewHomeStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldViewHomeStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldViewHomeStreetActionPerformed

    private void fieldViewHomeCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldViewHomeCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldViewHomeCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldViewHomeCity;
    private javax.swing.JTextField fieldViewHomeCountry;
    private javax.swing.JTextField fieldViewHomeStreet;
    private javax.swing.JTextField fieldViewHomeUnit;
    private javax.swing.JTextField fieldViewHomeZip;
    private javax.swing.JLabel lblViewHomeCity;
    private javax.swing.JLabel lblViewHomeCountry;
    private javax.swing.JLabel lblViewHomeStreet;
    private javax.swing.JLabel lblViewHomeTitle;
    private javax.swing.JLabel lblViewHomeUnit;
    private javax.swing.JLabel lblViewHomeZip;
    // End of variables declaration//GEN-END:variables


}
