/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.WorkArea.AdminRole.managePersonnelresp;

import Business.Business;
import Business.Person.Person;
import Business.Profile.EmployeeProfile;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hyungs
 */
public class AdministerPersonJPanel extends javax.swing.JPanel {
    
    JPanel workAreaJPanel;
    Business business;
    UserAccount userAccount;

    /**
     * Creates new form AdministerPersonJPanel
     */
    public AdministerPersonJPanel(Business b, JPanel workArea, UserAccount ua) {
        initComponents();
        
        this.business = b;
        this.workAreaJPanel = workArea;
        this.userAccount = ua;
        
        if (ua == null) {
            btnEmployeeSave.setEnabled(true);
            btnEmployeeUpdate.setEnabled(false);
        } else {
            btnEmployeeSave.setEnabled(false);
            btnEmployeeUpdate.setEnabled(true);
            populateFields();
        }
    }
    
        private void populateFields() {
            EmployeeProfile ep = (EmployeeProfile) userAccount.getAssociatedPersonProfile();
            
            txtEmployeeName.setText(ep.getName());
            txtEmployeeDept.setText(ep.getDepartment());
            txtEmployeeUserName.setText(userAccount.getUserLoginName());
            txtEmployeePw.setText(userAccount.getPassword());
            
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        lblEmployeeUserName = new javax.swing.JLabel();
        lblEmployeePw = new javax.swing.JLabel();
        lblEmployeeDept = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        txtEmployeeUserName = new javax.swing.JTextField();
        txtEmployeePw = new javax.swing.JTextField();
        txtEmployeeDept = new javax.swing.JTextField();
        btnEmployeeSave = new javax.swing.JButton();
        btnEmployeeUpdate = new javax.swing.JButton();
        btnEmployeeBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setText("Manage Person Profile");

        lblEmployeeName.setText("Name :");

        lblEmployeeUserName.setText("User Name :");

        lblEmployeePw.setText("Password :");

        lblEmployeeDept.setText("Department :");

        btnEmployeeSave.setText("Save");
        btnEmployeeSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeSaveActionPerformed(evt);
            }
        });

        btnEmployeeUpdate.setText("Update");
        btnEmployeeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeUpdateActionPerformed(evt);
            }
        });

        btnEmployeeBack.setText("<<< Back");
        btnEmployeeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployeeName)
                            .addComponent(lblEmployeeUserName)
                            .addComponent(lblEmployeePw)
                            .addComponent(lblEmployeeDept))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmployeeName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtEmployeeUserName)
                            .addComponent(txtEmployeePw)
                            .addComponent(txtEmployeeDept)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnEmployeeSave)
                        .addGap(119, 119, 119)
                        .addComponent(btnEmployeeUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnEmployeeBack)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnEmployeeBack)
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeName)
                    .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeUserName)
                    .addComponent(txtEmployeeUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeePw)
                    .addComponent(txtEmployeePw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeDept)
                    .addComponent(txtEmployeeDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmployeeSave)
                    .addComponent(btnEmployeeUpdate))
                .addContainerGap(219, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeSaveActionPerformed
        // TODO add your handling code here:
        String name = txtEmployeeName.getText();
        String department = txtEmployeeDept.getText();
        String un = txtEmployeeUserName.getText();
        String pw = txtEmployeePw.getText();
        
        if(name.isEmpty() || department.isEmpty() || un.isEmpty() || pw.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out all fields", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        UserAccountDirectory uad = business.getUserAccountDirectory();
        
        for (UserAccount existing : uad.getUserAccountList()) {
            if(existing.getUserLoginName().equalsIgnoreCase(un)) {
                JOptionPane.showMessageDialog(null, "Username already exist", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        Person p = new Person(un);
        
        EmployeeProfile ep = business.getEmployeeDirectory().newEmployeeProfile(p);
        ep.setName(name);
        ep.setDepartment(department);
        
        UserAccount ua = new UserAccount(ep,un,pw);
        uad.getUserAccountList().add(ua);
        ua.setLastUpdated(java.time.LocalDateTime.now().toString());
        
        JOptionPane.showMessageDialog(this, "Successfully created", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        
        txtEmployeeDept.setText("");
        txtEmployeeName.setText("");
        txtEmployeePw.setText("");
        txtEmployeeUserName.setText("");
        
    }//GEN-LAST:event_btnEmployeeSaveActionPerformed
    
    private void btnEmployeeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeBackActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_btnEmployeeBackActionPerformed
    private void backAction() {
        workAreaJPanel.remove(this);
        Component[] componentArray = workAreaJPanel.getComponents();
        Component component = componentArray[componentArray.length-1];
        ManagePersonJPanel mp = (ManagePersonJPanel) component;
        mp.refreshTable();
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
    }
    private void btnEmployeeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeUpdateActionPerformed
        // TODO add your handling code here:
        String name = txtEmployeeName.getText();
        String department = txtEmployeeDept.getText();
        String un = txtEmployeeUserName.getText();
        String pw = txtEmployeePw.getText();
        
        if(name.isEmpty() || department.isEmpty() || un.isEmpty() || pw.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out all fields", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        EmployeeProfile ep = (EmployeeProfile) userAccount.getAssociatedPersonProfile();
        ep.setName(name);
        ep.setDepartment(department);
        
        userAccount.setPassword(pw);
        userAccount.setLastUpdated(java.time.LocalDateTime.now().toString());
        
        
        JOptionPane.showMessageDialog(this, "Successfully updated", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        
        txtEmployeeDept.setText("");
        txtEmployeeName.setText("");
        txtEmployeePw.setText("");
        txtEmployeeUserName.setText("");
        
        backAction();
        
    }//GEN-LAST:event_btnEmployeeUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployeeBack;
    private javax.swing.JButton btnEmployeeSave;
    private javax.swing.JButton btnEmployeeUpdate;
    private javax.swing.JLabel lblEmployeeDept;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblEmployeePw;
    private javax.swing.JLabel lblEmployeeUserName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtEmployeeDept;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEmployeePw;
    private javax.swing.JTextField txtEmployeeUserName;
    // End of variables declaration//GEN-END:variables



}
