/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.WorkArea.AdminRole.managePersonnelresp;

import Business.Business;
import Business.Profile.EmployeeProfile;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hyungs
 */
public class ManagePersonJPanel extends javax.swing.JPanel {
    JPanel workAreaJPanel;
    Business business;
    UserAccount userAccount;

    /**
     * Creates new form ManagePersonJPanel
     */
    public ManagePersonJPanel(Business b, JPanel workArea, UserAccount ua) {
        initComponents();
        
        this.business = b;
        this.workAreaJPanel = workArea;
        this.userAccount = ua;
        
        refreshTable();

    }
    
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblManagePersonnelList.getModel();
        model.setRowCount(0);
        
        UserAccountDirectory uad = business.getUserAccountDirectory();
        
        for (UserAccount ua : uad.getUserAccountList()) {
            if (!(ua.getAssociatedPersonProfile() instanceof EmployeeProfile)) {
                continue;
            }
            EmployeeProfile ep = (EmployeeProfile) ua.getAssociatedPersonProfile();
            
            Object[] row = new Object[4];
            row[0] = ep.getName();
            row[1] = ua;
            row[2] = ep.getDepartment();
            row[3] = ua.getLastUpdated();
            
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManagePersonnelList = new javax.swing.JTable();
        btnHrAdd = new javax.swing.JButton();
        btnHrDelete = new javax.swing.JButton();
        btnHrNext = new javax.swing.JButton();
        btnHrBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setText("Manage Personnel (HR)");

        tblManagePersonnelList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "User Name", "Department", "Last Updated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManagePersonnelList);

        btnHrAdd.setText("Add");
        btnHrAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHrAddActionPerformed(evt);
            }
        });

        btnHrDelete.setText("Delete");
        btnHrDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHrDeleteActionPerformed(evt);
            }
        });

        btnHrNext.setText("Next >>>");
        btnHrNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHrNextActionPerformed(evt);
            }
        });

        btnHrBack.setText("<<< Back");
        btnHrBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHrBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHrBack)
                                .addGap(147, 147, 147)
                                .addComponent(lblTitle))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnHrAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnHrDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnHrNext)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHrBack)
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHrAdd)
                    .addComponent(btnHrDelete)
                    .addComponent(btnHrNext))
                .addContainerGap(308, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHrAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHrAddActionPerformed
        // TODO add your handling code here:
        AdministerPersonJPanel panel = new AdministerPersonJPanel(business, workAreaJPanel,null);
        workAreaJPanel.add("AdministerPersonJPanel", panel);
        
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
        
    }//GEN-LAST:event_btnHrAddActionPerformed

    private void btnHrNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHrNextActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManagePersonnelList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        UserAccount ua = (UserAccount) tblManagePersonnelList.getValueAt(selectedRow, 1);
        
        AdministerPersonJPanel panel = new AdministerPersonJPanel (business, workAreaJPanel, ua);
        workAreaJPanel.add("AdministerPersonJPanel", panel);
        
        CardLayout layout = (CardLayout)workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
        
    }//GEN-LAST:event_btnHrNextActionPerformed

    private void btnHrDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHrDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblManagePersonnelList.getSelectedRow();
        
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        UserAccount ua = (UserAccount) tblManagePersonnelList.getValueAt(row, 1);
        UserAccountDirectory uad = business.getUserAccountDirectory();
        uad.getUserAccountList().remove(ua);
        
        refreshTable();
        
    }//GEN-LAST:event_btnHrDeleteActionPerformed

    private void btnHrBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHrBackActionPerformed
        // TODO add your handling code here:
        workAreaJPanel.remove(this);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
        
    }//GEN-LAST:event_btnHrBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHrAdd;
    private javax.swing.JButton btnHrBack;
    private javax.swing.JButton btnHrDelete;
    private javax.swing.JButton btnHrNext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblManagePersonnelList;
    // End of variables declaration//GEN-END:variables





}
