package Ui.WorkArea.StudentRole.Student;


import Business.Business;
import Business.Person.Person;
import Business.Profile.StudentDirectory;
import Business.Profile.StudentProfile;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Hyungs
 */
public class SignUpJPanel extends javax.swing.JPanel {
    
    Business business;
    JPanel workAreaJPanel;


    /**
     * Creates new form SignUpJPanel
     */
    public SignUpJPanel(Business b, JPanel workArea) {
        initComponents();
        this.business = b;
        this.workAreaJPanel = workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblNuId = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblCreatePassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtNuId = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtCreatePassword = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JTextField();
        btnStudentSave = new javax.swing.JButton();
        btnStudentBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setText("Registration Form");

        lblNuId.setText("NUID: ");

        lblStudentName.setText("Student Name: ");

        lblCreatePassword.setText("Create Password: ");

        lblConfirmPassword.setText("Confirm Password:");

        lblUserName.setText("User Name:");

        btnStudentSave.setText("Save");
        btnStudentSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentSaveActionPerformed(evt);
            }
        });

        btnStudentBack.setText("<<< Back");
        btnStudentBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(280, 280, 280)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(213, 213, 213)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNuId)
                                .addComponent(lblStudentName))
                            .addGap(101, 101, 101)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNuId, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(txtStudentName)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(btnStudentBack))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUserName)
                                .addComponent(lblCreatePassword)
                                .addComponent(lblConfirmPassword))
                            .addGap(85, 85, 85)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUserName)
                                .addComponent(txtCreatePassword)
                                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(btnStudentSave)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnStudentBack)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lblNuId))
                    .addComponent(txtNuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentName)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreatePassword)
                    .addComponent(txtCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConfirmPassword)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnStudentSave)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentSaveActionPerformed
        // TODO add your handling code here:
        String name = txtStudentName.getText();
        String nuid = txtNuId.getText();
        String un = txtUserName.getText();
        String pw = txtCreatePassword.getText();
        String cpw = txtConfirmPassword.getText();
        
        if(name.isEmpty() || nuid.isEmpty() || un.isEmpty() || pw.isEmpty() || cpw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill out all fields.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!pw.equals(cpw)) {
            JOptionPane.showMessageDialog(this, "Password do not match", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        

        UserAccountDirectory uad = business.getUserAccountDirectory();
            for (UserAccount existing : uad.getUserAccountList()) {
                if (existing.getUserLoginName().equalsIgnoreCase(un)) {
                    JOptionPane.showMessageDialog(this, "Username already exist", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            
            
        StudentDirectory sd = business.getStudentDirectory();
        if (sd.findStudent(nuid)!=null) {
            JOptionPane.showMessageDialog(this, "NUID already exist", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
            }
        
        
        Person p = new Person (nuid);
        StudentProfile sp = sd.newStudentProfile(p);
        
        sp.setNuId(nuid);
        sp.setName(name);
        
        UserAccount ua = new UserAccount (sp,un,pw);
        uad.getUserAccountList().add(ua);
        
        ua.setLastUpdated(java.time.LocalDateTime.now().toString());
        ua.setLastActivity("");
        
        JOptionPane.showMessageDialog(this, "Successfully saved! Please login.", "information", JOptionPane.INFORMATION_MESSAGE);
        
        txtNuId.setText("");
        txtStudentName.setText("");
        txtUserName.setText("");
        txtCreatePassword.setText("");
        txtConfirmPassword.setText("");
        
        CardLayout layout = (CardLayout)workAreaJPanel.getLayout();
        layout.show(workAreaJPanel, "Student");

    }//GEN-LAST:event_btnStudentSaveActionPerformed

    private void btnStudentBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentBackActionPerformed
        // TODO add your handling code here:
        workAreaJPanel.remove(this);
        
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.show(workAreaJPanel, "Student");
    }//GEN-LAST:event_btnStudentBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentBack;
    private javax.swing.JButton btnStudentSave;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblCreatePassword;
    private javax.swing.JLabel lblNuId;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtConfirmPassword;
    private javax.swing.JTextField txtCreatePassword;
    private javax.swing.JTextField txtNuId;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
