/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.WorkArea.StudentRole.Student;

import Business.Business;
import Business.Profile.Profile;
import Business.Profile.StudentProfile;
import Business.UserAccount.UserAccount;
import Ui.WorkArea.StudentRole.StudentRoleWorkResp.StudentRegistrationJPanel;
import Ui.WorkArea.StudentRole.StudentRoleWorkResp.StudentWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hyungs
 */
public class StudentPortalJPanel extends javax.swing.JPanel {
    
    Business business;
    JPanel workAreaJPanel;
    UserAccount userAccount;
   

    /**
     * Creates new form StudentPortalJPanel
     */
    public StudentPortalJPanel(Business b, JPanel workArea, UserAccount userAccount) {
        initComponents();
        
        this.business = b;
        this.workAreaJPanel = workArea;
        this.userAccount = userAccount;

    }
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnStudentCourseWork = new javax.swing.JButton();
        btnStudentManageProfile = new javax.swing.JButton();
        btnStudentTranscript = new javax.swing.JButton();
        btnStudentRegistration = new javax.swing.JButton();
        btnGraduationAudit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setText("My Student Portal");

        btnStudentCourseWork.setBackground(new java.awt.Color(51, 153, 255));
        btnStudentCourseWork.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentCourseWork.setText("Course Work");
        btnStudentCourseWork.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentCourseWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentCourseWorkActionPerformed(evt);
            }
        });

        btnStudentManageProfile.setBackground(new java.awt.Color(51, 153, 255));
        btnStudentManageProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentManageProfile.setText("Mange Profile");
        btnStudentManageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentManageProfileActionPerformed(evt);
            }
        });

        btnStudentTranscript.setBackground(new java.awt.Color(51, 153, 255));
        btnStudentTranscript.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentTranscript.setText("Transcript");
        btnStudentTranscript.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentTranscriptActionPerformed(evt);
            }
        });

        btnStudentRegistration.setBackground(new java.awt.Color(51, 153, 255));
        btnStudentRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentRegistration.setText("Registration");
        btnStudentRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentRegistrationActionPerformed(evt);
            }
        });

        btnGraduationAudit.setBackground(new java.awt.Color(51, 153, 255));
        btnGraduationAudit.setForeground(new java.awt.Color(255, 255, 255));
        btnGraduationAudit.setText("Graduation Audit");
        btnGraduationAudit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGraduationAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduationAuditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStudentTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStudentManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStudentCourseWork, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(lblTitle)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentCourseWork, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnStudentTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentManageProfileActionPerformed
        // TODO add your handling code here:
        
        StudentWorkAreaJPanel panel = new StudentWorkAreaJPanel (business, workAreaJPanel, userAccount);
        
        workAreaJPanel.add("StudentWorkAreaJPanel", panel);
        
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.show(workAreaJPanel, "StudentWorkAreaJPanel");
        

    }//GEN-LAST:event_btnStudentManageProfileActionPerformed

    private void btnStudentCourseWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentCourseWorkActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This button is not included in the assignment.", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnStudentCourseWorkActionPerformed

    private void btnStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentRegistrationActionPerformed
        // TODO add your handling code here:
        StudentRegistrationJPanel panel = new StudentRegistrationJPanel (business, workAreaJPanel);
        
        workAreaJPanel.add("StudentRegistrationJPanel", panel);
        CardLayout layout = (CardLayout)workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
        
    }//GEN-LAST:event_btnStudentRegistrationActionPerformed

    private void btnGraduationAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduationAuditActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This button is not included in the assignment.", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGraduationAuditActionPerformed

    private void btnStudentTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentTranscriptActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This button is not included in the assignment.", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnStudentTranscriptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraduationAudit;
    private javax.swing.JButton btnStudentCourseWork;
    private javax.swing.JButton btnStudentManageProfile;
    private javax.swing.JButton btnStudentRegistration;
    private javax.swing.JButton btnStudentTranscript;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables


}
